#!/bin/bash

ID=$(grep -oP '(?<=^ID_LIKE=).+' /etc/os-release | tr -d '"')
echo $ID
var="debian"
if [ "$ID" = "$var" ]; then
sudo apt-get update
sudo apt-get install apache2
sudo systemctl start apache2
sudo systemctl enable apache2
cd /var/www/html
echo "This is ubuntu" > index.html
else
sudo yum update -y
sudo yum install -y httpd.x86_64
sudo systemctl start httpd.service
sudo systemctl enable httpd.service
cd /var/www/html
echo "This is Amazon Linux" > index.html
fi
