#!/bin/bash

ID=$(grep -oP '(?<=^ID_LIKE=).+' /etc/os-release | tr -d '"')
echo $ID
var="debian"

if [ "$ID" = "$var" ]; then
sudo apt-get update -y
sudo apt-get install ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update -y
sudo apt-get install docker-ce docker-ce-cli containerd.io -y
sudo systemctl start docker.service
sudo systemctl start containerd.service
sudo systemctl enable docker.service
sudo systemctl enable containerd.service
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker
echo "Hi I am docker nginx in Ubuntu">index.html
echo -e "FROM nginx\nCOPY index.html /usr/share/nginx/html/index.html\nCOPY index.html /usr/share/nginx/html/50x.html\nEXPOSE 80\nCMD [\"nginx\", \"-g\", \"daemon off;\"]">Dockerfile
docker build -t custom_nginx -f Dockerfile .
docker run -tid -p 80:80 custom_nginx
docker run -tid -p 81:80 nginx

else
sudo yum update -y
sudo amazon-linux-extras install docker
sudo yum install docker
sudo service docker start
sudo systemctl enable docker
sudo usermod -a -G docker ec2-user
echo "Hi I am docker nginx in Amazon Linux">index.html
echo -e "FROM nginx\nCOPY index.html /usr/share/nginx/html/index.html\nCOPY index.html /usr/share/nginx/html/50x.html\nEXPOSE 80\nCMD [\"nginx\", \"-g\", \"daemon off;\"]">Dockerfile
docker build -t custom_nginx -f Dockerfile .
docker run -tid -p 80:80 custom_nginx
docker run -tid -p 81:80 nginx
fi
